# Generated by Django 5.2.17 on 2026-09-17 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'estado'], name='turnos_turn_fecha_9956d7_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['usuario', 'fecha'], name='turnos_turn_usuario_b0342d_idx'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelado'), _negated=True), fields=('fecha', 'hora'), name='uniq_turno_activo_fecha_hora'),
        ),
    ]
