# Generated by Django 5.2.17 on 2026-09-17 20:41

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField()),
                ('motivo', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['fecha', 'desde'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='BARBERIA YESIT', max_length=120)),
                ('telefono', models.CharField(default='+57 300 123 4567', max_length=40)),
                ('direccion', models.CharField(default='Calle 13 #10-20', max_length=200)),
                ('descripcion', models.TextField(default='Cortes clásicos y modernos, arreglo de barba y atención de primera.')),
            ],
            options={
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(unique=True)),
                ('abierto', models.BooleanField(default=True)),
                ('desde', models.TimeField(default=datetime.time(8, 0))),
                ('hasta', models.TimeField(default=datetime.time(19, 0))),
            ],
            options={
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField(help_text='Minutos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('icono', models.CharField(choices=[('scissors', 'Tijeras'), ('beard', 'Barba'), ('combo', 'Combo'), ('crown', 'Premium')], default='scissors', max_length=20)),
            ],
            options={
                'ordering': ['precio', 'nombre'],
            },
        ),
    ]
